apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - chart: guestbook
      repoURL: https://apphub.aliyuncs.com/apphub
      targetRevision: 0.2.0