apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: nginx
      targetRevision: 15.2.1
      helm:
        valueFiles:
        - $values/environments/dev/dev-values.yaml
    - repoURL: 'https://github.com/Dinidu/argocd-example-apps.git'
      targetRevision: master
      ref: values