apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - repoURL: https://stefanprodan.github.io/podinfo
      chart: podinfo
      targetRevision: 6.4.1
      helm:
        valueFiles:
        - $values/environments/dev/dev-values.yaml
    - repoURL: 'https://github.com/Dinidu/argocd-example-apps.git'
      targetRevision: master
      ref: values